name: Lint & Format

on:
  pull_request:

jobs:
  format_lint:
      name: Format and Lint
      runs-on: ubuntu-latest
      steps:
        - uses: rome/setup-rome@v0.4
          with:
            version: latest 
        - run: rome check /web/src--apply-suggested
        - run: rome format /web/src --write